# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apodo_usuario', models.CharField(max_length=50)),
                ('bio', models.CharField(default='', max_length=140)),
                ('equipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuEq.Equipo')),
            ],
        ),
    ]
