# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipo_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
