# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0004_auto_20170103_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='empates',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_contra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_favor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_jugados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='victorias',
        ),
    ]
