# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0008_auto_20170104_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='identificador',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
