# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0009_partido_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='identificador',
        ),
    ]
