# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_viaje', models.IntegerField()),
                ('coste_viaje', models.IntegerField()),
                ('modo', models.CharField(max_length=20)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Destino')),
            ],
        ),
    ]
