# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=30)),
                ('coste_ruta', models.IntegerField()),
                ('dias_ruta', models.IntegerField()),
                ('destino1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino1', to='viajes.Destino')),
                ('destino2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino2', to='viajes.Destino')),
                ('destino3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino3', to='viajes.Destino')),
            ],
        ),
    ]
