# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('ciudad_equipo', models.CharField(max_length=50)),
                ('entrenador_equipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=50)),
                ('ciudad_natal', models.CharField(max_length=50)),
                ('edad_jugador', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('puntos_jugador', models.IntegerField()),
                ('valor_jugador', models.IntegerField()),
                ('equipo_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuEq.Equipo')),
            ],
        ),
    ]
