# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
