# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0003_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='goles_jugador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
