# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuEq', '0004_jugador_goles_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='goles_jugador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntos_jugador',
            field=models.IntegerField(default=0),
        ),
    ]
